version: '3.9'

services:
  app:
    build: .
    container_name: franchise-api
    ports:
      - "4400:4400"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQLUSER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLPASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 4400
    restart: on-failure
